import React from "react";

const Dots = () => {
  return (
    <>
      <div
        className={`flex flex-wrap items-start  justify-start gap-5 p-2  w-[150px] h-[150px] absolute top-9 right-[30px] `}
      >
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
        <div className="lg:bg-orange-500 bg-blue-700 rounded-full h-[5px] w-[5px] " />
      </div>

      <div
        className={`hidden md:flex flex-wrap items-start justify-start gap-5 p-2  w-[350px] h-[350px] absolute top-[20%] right-[40%] translate-x-16 rotate-[90deg] `}
      >
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-orange-500 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
      </div>

      <div
        className={`flex flex-wrap items-start justify-start gap-5 p-2  w-[150px] h-[150px] absolute bottom-9 left-[30px] lg:bottom-[-5rem] xl:bottom-[1rem] 2xl:top-[40%] `}
      >
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
        <div className="bg-sky-800 rounded-full h-[5px] w-[5px] " />
      </div>
    </>
  );
};

export default Dots;
